name: Local Lab CI/CD Pipeline

on:
  # This workflow triggers on any push to the 'feature/local-cicd-pipeline' branch
  push:
    branches:
      - 'feature/local-cicd-pipeline'

jobs:
  build-and-deploy:
    # This job will run on our local machine via the self-hosted runner
    runs-on: self-hosted

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Generate Unique Image Tag
        # We give this step an 'id' so we can reference its outputs later
        id: generate_tag
        run: echo "IMAGE_TAG=$($env:GITHUB_SHA.Substring(0, 7))" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: 3. Build and Tag Image Inside Minikube
        shell: powershell
        run: |
          minikube -p minikube docker-env | Invoke-Expression
          docker build -t resume-service:${{ steps.generate_tag.outputs.IMAGE_TAG }} .

      - name: 4. Update Kubernetes Manifest with New Image Tag
        shell: powershell
        run: |
          # We also use the step output here for the replacement
          (Get-Content -Path k8s\deployment.yaml -Raw) -replace 'resume-service:latest', 'resume-service:${{ steps.generate_tag.outputs.IMAGE_TAG }}' | Set-Content -Path k8s\deployment.yaml

      - name: 5. Deploy to Kubernetes
        run: kubectl apply -f k8s/